name: Packaging
on:
  - push
jobs:
  build_distro:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install build frontend
        run: python -m pip install build
      - name: Create Source Package
        run: python -m build --sdist
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./dist/*.tar.gz
  publish:
    name: Publish package to PyPI
      #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - build_distro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./dist 
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # package_dir: looks in ./dist by default.
          verbose: true # for Debug Information

